### ISSUE TITLE
#pragma once is not standard

### ISSUE THREAD

**Issue by fingolfin** [ionescu007/minlzma#2]
First off, very nice! I am still looking, and apologize for starting with a "complaint", albeit a very minor one: but you label this as a "standards-compliant C library", yet are using `#pragma once` which is a non-standard compiler extension. Luckily this would be easy to rectify by using good old standard include guards. :-)

**Comment by ionescu007** [comment]
Thank you for your comment. While I agree that #pragma once isn't "standard", here are the compilers supporting it:
```
Clang | Supported[8]
Comeau C/C++ | Supported[9]
Cray C and C++ | Supported[10] (since 9.0)
C++Builder XE3 | Supported[11]
Digital Mars C++ | Supported[12]
GCC | Supported[13] (since 3.4[6])
HP C/aC++ | Supported[14] (since at least A.06.12)
IBM XL C/C++ | Supported[15] (since 13.1.1)
Intel C++ Compiler | Supported[16]
Microsoft Visual C++ | Supported[17][18] (since 4.2)
NVIDIA CUDA Compiler | Supported (depending on the underlying host compiler)
Pelles C | Supported[19]
ARM DS-5 | Supported[20]
IAR C/C++ | Supported[21]
Keil CC 5 | Supported[22]
Oracle Developer Studio C/C++ | Supported[23] (since 12.5)
Portland Group C/C++ | Supported[24] (since at least 17.4)
TinyCC | Supported[25] (since April 2015)
```
I would argue that the benefits of the feature outweigh the fact it is technically not part of the standard specification. I am happy to edit the readme to replace 'standards-compliant' with something more appropriate, since the code also uses non int32_t based bitfields.

**Comment by fingolfin** [comment]
Honestly I fail to see the benefits, having an include guard provides the exact same service, and is 100% standards compliant?

Anyway, I won't complain either way -- either it shouldn't be used, or the claim not be made ;-). Well, or you can of course also leave it as it is, it's your project ;-).

**Comment by ionescu007** [comment]
Include guards can often times be slower since the preprocessor needs to be used (and associated state). `#pragma once` is recognized directly by the compiler. That being said, there were a number of other non-standard pragmas that I realized the project was using, and I removed them, so I thank you kindly for bringing them to my attention!
